# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20170314_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='type_of_vote',
            field=models.IntegerField(choices=[(1, 'Upvote'), (2, 'Downvote'), (3, 'Flag'), (4, 'Unflag')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('post', 'wbs')]),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([]),
        ),
    ]
