# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_auto_20170315_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wbs',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vote',
            name='type_of_vote',
            field=models.IntegerField(choices=[(1, 'Upvote'), (2, 'Downvote'), (3, 'Flag')]),
        ),
    ]
